# (c) 2016 DataNexus Inc.  All Rights Reserved
---
- name: Enable the telegraf agents on boot
  become: true
  service:
    name: "telegraf-{{item}}"
    enabled: yes
  with_items:
    - metrics
    - logs
