# (c) 2016 DataNexus Inc.  All Rights Reserved
---
- block:
  - name: Delete default telegraf configuration file
    file:
      path: /etc/telegraf/telegraf.conf
      state: absent
  - name: Generate new telegraf configuration files
    shell: "telegraf -input-filter {{input_filters[item]}} -output-filter {{output_filters[item]}} config > /etc/telegraf/telegraf-{{item}}.conf"
    with_items:
      - metrics
      - logs
  - set_fact:
      kfka_nodes_str: "{{kfka_nodes | join(':9092\",\"')}}"
  - name: Configure telegraf to report metrics to Kafka
    replace:
      dest: /etc/telegraf/telegraf-metrics.conf
      regexp: "{{ item.regexp }}"
      replace: "{{ item.replace }}"
    with_items:
      - { regexp: '^(#)?(.*)precision = (.*)$' , replace: '\g<2>precision = "1ns"' }
      - { regexp: '^(#)?(.*)kafka(.*)$' , replace: '\g<2>kafka\g<3>' }
      - { regexp: '^(#)?(.*)topic = "telegraf"(.*)$' , replace: '\g<2>topic = "metrics"\g<3>' }
      - { regexp: '^(#)?(.*)localhost(:9092.*)$' , replace: '\g<2>{{kfka_nodes_str}}\g<3>' }
      - { regexp: '^([^#])(.*)routing_tag(.*)$' , replace: '#\g<1>\g<2>routing_tag\g<3>' }
      - { regexp: '^(#)?(.*)data_format = "influx"(.*)$' , replace: '\g<2>data_format = "json"\g<3>' }
  - name: Configure telegraf to report logs to Kafka
    replace:
      dest: /etc/telegraf/telegraf-logs.conf
      regexp: "{{ item.regexp }}"
      replace: "{{ item.replace }}"
    with_items:
      - { regexp: '^(#)?(.*)precision = (.*)$' , replace: '\g<2>precision = "1ns"' }
      - { regexp: '^(#)?(\s*)files = (.*)$' , replace: '\g<2>files = {{log_paths | to_json}}' }
      - { regexp: '^(#)?(.*)from_beginning = (.*)$' , replace: '\g<2>from_beginning = {{(log_parse_from_beginning | default(false)) | lower}}' }
      - { regexp: '^(#)?(.*)measurement = (.*)$' , replace: '\g<2># measurement = \g<3>' }
      - { regexp: '^(#)?(.*)custom_pattern_files = (.*)$' , replace: '\g<2># custom_pattern_files = \g<3>' }
      - { regexp: '^(#)?(.*)kafka(.*)$' , replace: '\g<2>kafka\g<3>' }
      - { regexp: '^(#)?(.*)topic = "telegraf"(.*)$' , replace: '\g<2>topic = "logs"\g<3>' }
      - { regexp: '^(#)?(.*)localhost(:9092.*)$' , replace: '\g<2>{{kfka_nodes_str}}\g<3>' }
      - { regexp: '^([^#])(.*)routing_tag(.*)$' , replace: '#\g<1>\g<2>routing_tag\g<3>' }
      - { regexp: '^(#)?(.*)data_format = "influx"(.*)$' , replace: '\g<2>data_format = "json"\g<3>' }
  - set_fact:
      keys_prefix: '"%{'
      keys_sep: '}","%{'
      keys_suffix: '}"'
  - set_fact:
      joined_keys: '{{ keys_prefix + (log_patterns.keys() | join(keys_sep)) + keys_suffix }}'
  - name: Add custom_patterns to the telegraf-logs configuration
    lineinfile:
      dest: /etc/telegraf/telegraf-logs.conf
      regexp: "^(\\s+)'''$"
      line: "      {{item.key}} {{item.value}}\n    '''"
      insertbefore: yes
      state: present
    with_dict: "{{log_patterns}}"
  - name: Add patterns the telegraf-logs configuration
    replace:
      dest: /etc/telegraf/telegraf-logs.conf
      regexp: '^((\s)*patterns\s*=\s*\[).*(\])$'
      replace: '\g<1>{{joined_keys}}\g<3>'
  become: true
