# (c) 2016 DataNexus Inc.  All Rights Reserved
---
- include: install-telegraf.yml static=no
- include_role:
    name: configure-telegraf-nodes
    tasks_from: generate-new-telegraf-configs
- include: create-telegraf-service.yml static=no
- include: start-telegraf-service.yml static=no
- include: enable-telegraf-service.yml static=no
