# (c) 2016 DataNexus Inc.  All Rights Reserved
---
- block:
  - name: Configure telegraf to report logs to Kafka
    replace:
      dest: "/etc/telegraf/telegraf.d/telegraf-{{measurement_type}}.conf"
      regexp: "{{ item.regexp }}"
      replace: "{{ item.replace }}"
    with_items:
      - { regexp: '^(#)?(\s*)files = (.*)$' , replace: '\g<2>files = {{log_paths | to_json}}' }
      - { regexp: '^(#)?(.*)from_beginning = (.*)$' , replace: '\g<2>from_beginning = {{(log_parse_from_beginning | default(false)) | lower}}' }
      - { regexp: '^(#)?(.*)measurement = (.*)$' , replace: '\g<2># measurement = \g<3>' }
      - { regexp: '^(#)?(.*)custom_pattern_files = (.*)$' , replace: '\g<2># custom_pattern_files = \g<3>' }
  # and configure the logs output with some custom patterns
  - set_fact:
      keys_prefix: '"%{'
      keys_sep: '}","%{'
      keys_suffix: '}"'
  - set_fact:
      joined_keys: '{{ keys_prefix + (log_patterns.keys() | join(keys_sep)) + keys_suffix }}'
  - name: Add custom_patterns to the telegraf configuration
    lineinfile:
      dest: "/etc/telegraf/telegraf.d/telegraf-{{measurement_type}}.conf"
      insertbefore: "^(\\s+)'''$"
      line: '      {{item.key}} {{item.value}}'
      state: present
    with_dict: "{{log_patterns}}"
  - name: Add patterns the telegraf configuration
    replace:
      dest: "/etc/telegraf/telegraf.d/telegraf-{{measurement_type}}.conf"
      regexp: '^((\s)*patterns\s*=\s*\[).*(\])$'
      replace: '\g<1>{{joined_keys}}\g<3>'
  become: true
