# (c) 2016 DataNexus Inc.  All Rights Reserved
---
- block:
  # first, generate a new configuration file using the `telegraf` command and
  # the input and output filters defined in the playbook run
  - name: Delete default telegraf configuration file
    file:
      path: /etc/telegraf/telegraf.conf
      state: absent
  - name: Generate a new telegraf configuration file in place of the default
    shell: "telegraf -input-filter {{item.input_filter}} -output-filter {{item.output_filter}} config > /etc/telegraf/telegraf.d/telegraf-{{item.type}}.conf"
    with_items: "{{telegraf_measurements}}"
  become: true
